language: node_js
node_js: lts/*
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.10
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install:
  - cd ./my-app && yarn install
script:
  - yarn build
  - yarn test a
  - q
